title = "Status page"

[consul]

# The base url for the consul instance.
base_url = "http://example.com/"

# The names of the services for which the status should be displayed.
services = [
	"foo",
	"bar",
	"baz"
]
