title = "Status page"

[consul]

# The base url for the consul instance to talk to.
base_url = "http://example.com/"

# Number of seconds to wait for a response from Consul
timeout = 5

# Services are arranged in 1 or more groups

# [[service_group]]
# name = "A Group"
# 
# 	[[service_group.services]]
# 	name = "dashboard"
# 	description = "some description text. The description field is optional."
# 
# 	[[service_group.services]]
# 	name = "another_service"
# 
# [[service_group]]
# name = "Another Group"
# 
# 	[[service_group.services]]
# 	name = "apple"
# 	description = "The apple service"
# 
# 	[[service_group.services]]
# 	name = "orange"
# 	description = "The orange service"
